# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 18:14
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousTip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('incident_time', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('upload_evidence', models.BooleanField()),
                ('stay_in_touch', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AnonymousUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anonymous User',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, upload_to=home.models.evidence_upload_location)),
                ('image2', models.ImageField(blank=True, upload_to=home.models.evidence_upload_location)),
                ('doc', models.FileField(blank=True, upload_to=home.models.evidence_upload_location)),
                ('video', models.FileField(blank=True, upload_to=home.models.evidence_upload_location)),
                ('anonymous_tip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.AnonymousTip')),
            ],
        ),
        migrations.AddField(
            model_name='anonymoustip',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.AnonymousUser'),
        ),
    ]
